### ISSUE TITLE
执行『TrustAI示例』出错

### ISSUE THREAD

**Issue by Tangzy7** [PaddlePaddle/TrustAI#36]
执行『TrustAI示例』- 解决训练数据存在脏数据的问题 的时候，https://aistudio.baidu.com/aistudio/projectdetail/4434058

执行：
`python -u find_dirty_data.py --dataset_dir ./data --train_file train_5000.tsv  --num_classes 2  --rest_path ./data/rest_train.tsv --init_from_ckpt ./checkpoint/model_state.pdparams  --dirty_path ./data/dirty_train.tsv --dirty_num 500
`

出现错误：
`NotImplementedError: (Unimplemented) Invalid dimension to be accessed. Now only supports access to dimension 0 to 9, but received dimension is 32. (at /paddle/paddle/fluid/framework/ddim.h:54)`

**Comment by zhangyimi** [comment]
你好，错误没有复现出来，我使用的的v100 16G的运行环境，可以新建环境再试一下

**Comment by Tangzy7** [comment]
> 

我也是v100 16G，新建环境还是没解决，看起来是框架的问题。。。。因为我都是按示例的命令执行的，而且去除脏数据前的模型也能训练

**Comment by Tangzy7** [comment]
> 你好，错误没有复现出来，我使用的的v100 16G的运行环境，可以新建环境再试一下


我也是v100 16G，新建环境还是没解决，看起来是框架的问题。。。。因为我都是按示例的命令执行的，而且去除脏数据前的模型也能训练
