### ISSUE TITLE
paddleNLP 中的zero_shot_text_classification可以用TrustAI解释分析单词的重要度吗？

### ISSUE THREAD

**Issue by magicleo** [PaddlePaddle/TrustAI#52]
请问zero_shot_text_classification 可以用基于TrustAI解释分析单词的重要度吗？
有没有demo可以参考下？

**Comment by wanglijiehit** [comment]
TrustAI的分析依赖模型提供attention、梯度等信息，当前基于大模型的任务还不能通过TrustAI提供单词重要度。
