### ISSUE TITLE
请问贵组招实习生吗

### ISSUE THREAD

**Issue by jc-ryan** [PaddlePaddle/TrustAI#8]
如题，可尽快到岗

**Comment by zhangyimi** [comment]
可以先将简历发送到zhangshuai28@baidu.com，谢谢

**Comment by jc-ryan** [comment]
> 可以先将简历发送到[zhangshuai28@baidu.com](mailto:zhangshuai28@baidu.com)，谢谢

好的谢谢

**Comment by crazyofapple** [comment]
贵组招应届博吗

**Comment by zhangyimi** [comment]
> 贵组招应届博吗

可以发送简历到上面的邮箱哈，我们先了解一下
